name: komby_bento_inventory
description: Komby Bento Warehouse Inventory Application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.0  # perbaikan di sini, langsung tanpa subkey 'dependencies'
  pdf: ^3.10.4
  printing: ^5.11.0
  fl_chart: ^0.63.0
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
